### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by SadiqNacerodien** [avishkar58/primate#20] opened 2016-05-30 20:22 UTC
Can we implement logging per instance of PRIMate? We will also need global logging across all instances at some stage. 

Probably more detailed logging on an instance level.

Maybe we just make it simple in the beginning...who logs in and when they log out. Can add actions later. We may want to log who creates new levels or members with the 1st set of logging

**Comment by avishkar58** [comment] 2016-05-30 20:51
Duplicate of #11 - closing and added as comments to that issue

**Closed by avishkar58** 2016-05-30 20:51 UTC
